# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(624, 801)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.startLE = QtWidgets.QLineEdit(self.groupBox)
        self.startLE.setObjectName("startLE")
        self.horizontalLayout_4.addWidget(self.startLE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.startResultL = QtWidgets.QLabel(self.groupBox)
        self.startResultL.setEnabled(True)
        self.startResultL.setText("")
        self.startResultL.setObjectName("startResultL")
        self.verticalLayout_2.addWidget(self.startResultL)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.endLE = QtWidgets.QLineEdit(self.groupBox)
        self.endLE.setObjectName("endLE")
        self.horizontalLayout_5.addWidget(self.endLE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.endResultL = QtWidgets.QLabel(self.groupBox)
        self.endResultL.setEnabled(True)
        self.endResultL.setText("")
        self.endResultL.setObjectName("endResultL")
        self.verticalLayout_2.addWidget(self.endResultL)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.findLocPB = QtWidgets.QPushButton(self.groupBox)
        self.findLocPB.setObjectName("findLocPB")
        self.horizontalLayout.addWidget(self.findLocPB)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.distanceL = QtWidgets.QLabel(self.groupBox_2)
        self.distanceL.setText("")
        self.distanceL.setObjectName("distanceL")
        self.verticalLayout_3.addWidget(self.distanceL)
        self.durationL = QtWidgets.QLabel(self.groupBox_2)
        self.durationL.setText("")
        self.durationL.setObjectName("durationL")
        self.verticalLayout_3.addWidget(self.durationL)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.hoursLE = QtWidgets.QLineEdit(self.groupBox_2)
        self.hoursLE.setEnabled(False)
        self.hoursLE.setObjectName("hoursLE")
        self.horizontalLayout_2.addWidget(self.hoursLE)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.mapPB = QtWidgets.QPushButton(self.groupBox_2)
        self.mapPB.setEnabled(False)
        self.mapPB.setObjectName("mapPB")
        self.horizontalLayout_3.addWidget(self.mapPB)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 624, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map my move"))
        self.groupBox.setTitle(_translate("MainWindow", "Find locations"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Spelling counts! US locations only. </p></body></html>"))
        self.label.setText(_translate("MainWindow", "Start:"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Spelling counts! US locations only.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "End:"))
        self.findLocPB.setText(_translate("MainWindow", "Search locations"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Drive time"))
        self.label_4.setText(_translate("MainWindow", "I would like to drive"))
        self.hoursLE.setToolTip(_translate("MainWindow", "<html><head/><body><p>Calculates +/- 30 mins of driving. Assumes avg speed of 70 mph</p></body></html>"))
        self.hoursLE.setText(_translate("MainWindow", "8"))
        self.label_3.setText(_translate("MainWindow", "hours per day"))
        self.mapPB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click here to see your route!</p></body></html>"))
        self.mapPB.setText(_translate("MainWindow", "Map my route!"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit program"))
